### ISSUE TITLE
需要有方法可以測試 query

### ISSUE THREAD

**Issue by evan361425** [evan361425/flutter-pos-system#122]
database methods 和 app 各種 query 都要測試

**Comment by evan361425** [comment]
https://docs.flutter.dev/cookbook/testing/integration/profiling

**Comment by evan361425** [comment]
wait for `flavor` on test, issue: https://github.com/flutter/flutter/pull/89045

After fixed, it should be able to add flavor in test:

```dart
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:possystem/services/image_dumper.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('ImageDumper', () {
    testWidgets('#pick', (tester) async {
      print('go!');
      final path = await ImageDumper.instance.getPath('abc');
      print(path);
    });
  });
}
```

**Comment by evan361425** [comment]
Also need to add coverage on integration test:

```yaml
 name: "Run Flutter Driver tests"
        # Operation for installing, configuring and running Android emulator
        # https://github.com/marketplace/actions/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: "flutter drive --target=test_driver/driver.dart"
```
